### ISSUE TITLE
Tax Task List marked as complete

### ISSUE THREAD

**Issue by warrendholmes** [Automattic/wc-calypso-bridge#1288]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I just started a new Woo Express store and the Tax task is marked as complete : 

<img width="723" alt="Screenshot 2023-08-30 at 14 59 17" src="https://github.com/Automattic/wc-calypso-bridge/assets/995473/2b5b435b-b6ec-4276-a9f2-fc71d8ae1d47">

The site url is https://woo-softly-valiant-gardener.wpcomstaging.com/ in case that's helpful.

### Expected behavior

Tax task list shouldn't be completed on sign up.

### Actual behavior

NA

### Steps to reproduce

NA

### WordPress Environment

NA

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.
