### ISSUE TITLE
[Epic] Update E2E tests to use WC Nightly and default cart/checkout/order-confirmed blocks

### ISSUE THREAD

**Issue by PanosSynetos** [Automattic/wc-calypso-bridge#1358]
Let's use this issue/pull requests, to track progress on SomewhereWarm plugins included in Woo Express

- [x] https://github.com/woocommerce/woocommerce-back-in-stock-notifications/pull/258 (@PanosSynetos)
- [x] https://github.com/woocommerce/woocommerce-min-max-quantities/pull/276 (@PanosSynetos)
- [x] https://github.com/woocommerce/woocommerce-product-addons/pull/929 (@PanosSynetos)
- [x] https://github.com/woocommerce/woocommerce-product-bundles/pull/1280 (@jimjasson )
- [x] https://github.com/woocommerce/woocommerce-conditional-shipping-and-payments/pull/611 (@jimjasson)
- [x] https://github.com/woocommerce/woocommerce-gift-cards/pull/726 (@jimjasson)
- [x] https://github.com/woocommerce/woocommerce-all-products-for-subscriptions/pull/609 (@jimjasson)
- [x] https://github.com/woocommerce/woocommerce-composite-products/pull/1048 (@jimjasson)

**Comment by PanosSynetos** [comment]
All PRs are ready and waiting for WC 8.3.0 to be released to merge them
