### ISSUE TITLE
[Epic] Update release scripts after plugins rebranding

### ISSUE THREAD

**Issue by jimjasson** [Automattic/wc-calypso-bridge#1388]
### Description

Similar to: https://github.com/woocommerce/woocommerce-product-addons/pull/942/commits/9d1e3fb1f9d04a73bfdd4113280e737e7f5d9168

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-product-bundles/pull/1286
- [ ] https://github.com/woocommerce/woocommerce-composite-products/pull/1051
- [ ] https://github.com/woocommerce/woocommerce-conditional-shipping-and-payments/pull/615
- [ ] https://github.com/woocommerce/woocommerce-gift-cards/pull/731
- [ ] https://github.com/woocommerce/woocommerce-all-products-for-subscriptions/pull/613
- [ ] https://github.com/woocommerce/woocommerce-back-in-stock-notifications/pull/262
- [ ] https://github.com/woocommerce/woocommerce-product-recommendations/pull/511
- [ ] https://github.com/woocommerce/woocommerce-min-max-quantities/pull/279
- [ ] https://github.com/woocommerce/woocommerce-product-addons/pull/942
```

**Comment by PanosSynetos** [comment]
All PRs have been merged. Closing
