### ISSUE TITLE
[Epic] Remove Woo Blocks dependency from CI tests

### ISSUE THREAD

**Issue by PanosSynetos** [Automattic/wc-calypso-bridge#1389]
### Description

Blocks are now merged in core, we should remove any dependencies

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-product-bundles/pull/1287
- [ ] https://github.com/woocommerce/woocommerce-composite-products/pull/1053
- [ ] https://github.com/woocommerce/woocommerce-conditional-shipping-and-payments/pull/616
- [ ] https://github.com/woocommerce/woocommerce-all-products-for-subscriptions/pull/614
- [ ] https://github.com/woocommerce/woocommerce-gift-cards/pull/735
- [ ] https://github.com/woocommerce/woocommerce-back-in-stock-notifications/pull/263
- [ ] https://github.com/woocommerce/woocommerce-product-addons/pull/943
- [ ] https://github.com/woocommerce/woocommerce-min-max-quantities/pull/281
```

Product Recommendations does not run E2E tests

**Comment by PanosSynetos** [comment]
Done, all PRs have been merged
