### ISSUE TITLE
Implementing and adjusting the new onboarding

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wc-calypso-bridge#529]
Following the plan to improve the store creation/management experience, we're going to implement the new onboarding experience in the eCommerce plan:

- [ ] In terms of flow it should be pretty the same that we have right now: when the user finishes the eCommerce plan purchase, he will be redirected to the Store Profiler. When he finishes the profiler (or skips it) he should land in the task list.

We need to make some adjustments in the profiler for the eCommerce plan users:
- [ ] Adjusting to Calypso: we're going to postpone implementing the new nav and removing Calypsoify, so we'll need to adjust the new onboarding to Calypsoify.
- [x] Product Types step: remove the paid products (users just paid the 1/2 year plan and we don't want them having second thoughts about why those extensions are not included in the plan. We'll review the product bundle in the plan in the near future)
- [x] Business Details step: remove the prompt to install marketing extensions (Facebook and Mailchimp are already included in the plan and we'll see in the future if it will be possible to also include Google Ads)
- [x] Theme step: just display Storefront and the child themes that are included in the plan (Galleria, Homestore and Bookshop). We should also display the current active theme (if the user has any and the option to upload a theme). The all/paid/free themes tab should be removed as well as the pricing, considering that all the themes that we're going to display are included in the plan.
- [x] Jetpack & WCS splash screen: remove the screen (I’m assuming that it will be automatically removed anyway as they are installed by default)
- [x] Opt-in users by default to usage tracking (#534)
- [ ] Remove usage tracking message at the beginning of the onboarding (#534)
- [x] Hide the tracking option from the Settings | Advanced | WooCommerce.com page (#534)
- [ ] It would be nice to add the same copy that we have right now at the end of the task list: Need help? Read the [eCommerce plan support document](https://en.support.wordpress.com/ecommerce-plan/) or get in touch with [support](https://wordpress.com/help/contact).

It won't be necessary to implement any change in the task list. In the future we should evaluate if it makes sense to have a task for the shipping live rates extensions included in the plan

**Comment by pmcpinto** [comment]
cc @jameskoster @timmyc for additional feedback

**Comment by jameskoster** [comment]
Re the task list, there are a couple of low-hanging-fruit changes we could potentially make:

1. Remove the tax task if the user is in a geography that supports automatic tax calculations. We should just enable that for them.
2. For shipping - we can enable label printing, and we'll know the store location from the wpcom signup flow(?), so we can remove those steps. Could we also remove the step where the user inputs some basic rates? Just enable free shipping by default and remove the shipping task entirely?
3. Probably not something for this release, but we might consider sending people directly to the wcpay signup flow for the payments task?

**Comment by pmcpinto** [comment]
> Remove the tax task if the user is in a geography that supports automatic tax calculations. We should just enable that for them

> For shipping - we can enable label printing, and we'll know the store location from the wpcom signup flow(?), so we can remove those steps.

Sounds good to me

> Could we also remove the step where the user inputs some basic rates? Just enable free shipping by default and remove the shipping task entirely?

I think that it would be good to keep it for the initial release. It's better than seeing the user going to the Shipping settings to double-check them :)

> Probably not something for this release, but we might consider sending people directly to the wcpay signup flow for the payments task?

That would be good for a second release.

**Comment by timmyc** [comment]
Thanks for creating the issue Pedro, these all seem reasonable to me.

**Comment by timmyc** [comment]
Adding a note to reflect that the current use of the legacy OBW is using the Stripe flow to auto-provision an account which is being sunset at the end of May. I mentioned this to @LCmry as work is being coordinated now in wc-admin ( https://github.com/woocommerce/woocommerce-admin/pull/4164 ) to update the Stripe setup flow.

<img width="1792" alt="WooCommerce › Setup Wizard - (Private Browsing) 2020-04-22 09-47-30" src="https://user-images.githubusercontent.com/22080/80010908-f7b88700-847f-11ea-83e5-5e7b18332005.png">

This issue here will effectively remove the legacy Stripe setup code in favor of what is in wc-admin, but just wanted to note that we need to ensure this fix ships prior to the cut-off date for the Stripe changes.

**Comment by timmyc** [comment]
Logging some notes on discovery here to update the estimate of the scope:

> Product Types step: remove the paid products (users just paid the 1/2 year plan and we don't want them having second thoughts about why those extensions are not included in the plan. We'll review the product bundle in the plan in the near future)

This looks like it should be easily done using the `woocommerce_admin_onboarding_product_types` filter [code here](https://github.com/woocommerce/woocommerce-admin/blob/master/src/Features/Onboarding.php#L269)

> Business Details step: remove the prompt to install marketing extensions (Facebook and Mailchimp are already included in the plan and we'll see in the future if it will be possible to also include Google Ads)

This one might be a bit more challenging. Currently we don't have a filter set for these promoted extensions - rather they are hard-coded into the JS [here](https://github.com/woocommerce/woocommerce-admin/blob/ea368e4e12ef7366e8dc1478f4404f1883e19ec0/client/profile-wizard/steps/business-details.js#L326-L357).  We could explore a css based solution here possibly and hide the `woocommerce-profile-wizard__benefit` div which shows the extensions, along with trying to get creative around the install of extensions on the REST API side of things too. This feels a bit problematic to me though / could get ugly. Here is a quick screen grab of what this could look like via CSS, guessing we could probably hide the paragraph about which plugins will be installed:

![image](https://user-images.githubusercontent.com/22080/81122297-7d5b1e80-8ee5-11ea-92ed-efa6fe3b3861.png)

Question - aren't we contractually obligated to show these options?

Ideal solution here would be to add a filter to wc-admin on that list of extensions that are promoted. @pmcpinto based off of that, not sure if this is possible without a new release of wc-admin with this targeted change - otherwise we need to just try to css/hacky solution above.

> Theme step: just display Storefront and the child themes that are included in the plan (Galleria, Homestore and Bookshop). We should also display the current active theme (if the user has any and the option to upload a theme). The all/paid/free themes tab should be removed as well as the pricing, considering that all the themes that we're going to display are included in the plan.

Filtering the array of themes looks easy enough to do also since we have the `woocommerce_admin_onboarding_themes` filter to leverage [code here](https://github.com/woocommerce/woocommerce-admin/blob/master/src/Features/Onboarding.php#L341)

Manipulating the tabs that are shown on this step though might prove to be difficult. Again the tabs themselves are hard-coded in the wc-admin code [here](https://github.com/woocommerce/woocommerce-admin/blob/ea368e4e12ef7366e8dc1478f4404f1883e19ec0/client/profile-wizard/steps/theme/index.js#L371-L384). The simplest option I can see is just to hide the tabs altogether via CSS. Only the themes outlined above would be shown which we have full control over via the filter:

![hide-tabs](https://user-images.githubusercontent.com/22080/81122385-a24f9180-8ee5-11ea-8017-739dd99b890f.png)

> Jetpack & WCS splash screen: remove the screen (I’m assuming that it will be automatically removed anyway as they are installed by default)

Confirmed [per the code](https://github.com/woocommerce/woocommerce-admin/blob/ea368e4e12ef7366e8dc1478f4404f1883e19ec0/client/profile-wizard/index.js#L162-L165) that this step shouldn't be shown because both JP and WCS will be installed + active at this point on ecom sites.

> Remove tracking modal in profiler

This will be another one that will require a change in wc-admin itself. The display of this modal currently has no filter available, and the display of it is based upon a state variable on that particular step.

Also wondering if we would want to remove the "Setting up a Store for a Client" part of this screen since it feels unlikely that a builder would purchase an ecomm plan on behalf of a client:

![image](https://user-images.githubusercontent.com/22080/81122864-b2b43c00-8ee6-11ea-9913-3aeb5fc3da1a.png)

Regardless, to get the usage modal to go away, we will need to add logic to wc-admin to allow suppression of that dialog via a filter.

The balance of the items around the tracking changes should all be do-able

**Comment by pmcpinto** [comment]
> Question - aren't we contractually obligated to show these options?

MC and FB are included in the eCommerce plan, so I don't make sense to display them. Let me ping Aleksandra about the Ads extension.

**Comment by pmcpinto** [comment]
>  Let me ping Aleksandra about the Ads extension.

We don't need to include it. Probably in Q3.

> Ideal solution here would be to add a filter to wc-admin on that list of extensions that are promoted. @pmcpinto based off of that, not sure if this is possible without a new release of wc-admin with this targeted change - otherwise we need to just try to css/hacky solution above.

I'd go with the easiest solution and it can always be polished later.

**Comment by timmyc** [comment]
> Adjusting to Calypso: we're going to postpone implementing the new nav and removing Calypsoify, so we'll need to adjust the new onboarding to Calypsoify.

While working on items today, I noticed that we already have some styling updates applied to the new profile wizard that Justin worked on. So I think we can check this item off, but definitely would like @jameskoster to go through the profiler flow on a test site to ensure things look good to him once we have all the items fixed up on this issue.

**Comment by timmyc** [comment]
> Jetpack & WCS splash screen: remove the screen (I’m assuming that it will be automatically removed anyway as they are installed by default)

Verified that when Jetpack and WCS are installed and active, the "benefits" step to install them is not shown.

**Comment by jameskoster** [comment]
> but definitely would like @jameskoster to go through the profiler flow on a test site to ensure things look good to him

For sure, please just let me know when you're ready for that!

**Comment by pmcpinto** [comment]
@jameskoster @timmyc probably we'll need to hide WCPay as it's still not included in the eCommerce package and the extension isn't adjusted to the eCommerce menu - the user would need to go to wpadmin, in order to access the WCPay dashboard

**Comment by pmcpinto** [comment]
I'm going to close this issue, as the onboarding was already shipped
