### ISSUE TITLE
Registering Plugins as Store Extensions

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wc-calypso-bridge#63]
This task includes creating a system for registering certain plugins (WooCommerce + extensions) as store extensions so they show up in the correct menus, and registering support for extension catalog. We will start with the extensions that are part of our bundle, followed by our top selling products.

If we can implement our entire catalog in the time frame, we should - but maybe the top ~25% can satisfy the initial launch?

The extension list to follow is here: p90Yrv-Po-p2

- [x] Create a system for registering plugins (#58)
- [x] Add support for bundled extensions (#59)
- [x] Add support for the WooCommerce extension catalog (#66).

**Comment by justinshreve** [comment]
Closing this out since the top 25% of our extensions are supported. We can continue to add more ad-hoc from the list.
