### ISSUE TITLE
Setup Task List

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wc-calypso-bridge#64]
This task involves creating a setup task list screen to help walk our new eCommerce users through setup of their store. 

On the tech side of things, we have agreed to keep v1 basic and just copy HTML/CSS from Calypso and fit it to our needs.

* [x] Create base task list based on Calypso styles
* [x] Implement static task text and action buttons
* [x] Create a method for tracking if a task has been completed
* [x] Create a method for dismissing the entire setup list
