### ISSUE TITLE
Hide notices that are a part of the setup task list

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wc-calypso-bridge#65]
See #64.

A number of the extensions we are bundling show notices right after installation. We can suppress the ones we are including on the setup task list.

**Comment by justinshreve** [comment]
The following notices are displayed after activating extensions that we are bundling:

# 
Notices Added:

* Facebook for WooCommerce is almost ready. To complete your configuration, complete the setup steps.
* Connect your store to WooCommerce.com to receive extensions updates and support.
* Klarna Order Management for WooCommerce is not active. Please activate it so you can capture, cancel, update and refund Klarna orders.
* Klarna Order Management is not active. Please activate it so you can capture, cancel, update and refund Klarna orders.
* Thanks for installing WooCommerce Product Add-ons.

Before diving in, we highly recommend getting to grips with per product add-ons and global add-ons in the documentation.

Ready to get started? Add a global add-on.
* Thanks for installing Storefront Powerpack. To get started, visit the Customizer.
* TaxJar for WooCommerce is almost ready. To get started, connect your TaxJar account.
* PayPal Checkout is almost ready. To get started, connect your PayPal account.
* Connect your Canada Post Account – Before you can start using Canada Post you need to register for an account, or connect an existing one.

@josemarques I just wanted to double check. We are hiding these because they will be shown on the check-list page instead, correct?

**Comment by jeffikus** [comment]
So far I have tested with the following extensions:

- [ ] Facebook for WooCommerce
- [ ] Klarna Checkout for WooCommerce
- [ ] Klarna Payments for WooCommerce
- [ ] Mailchimp for WooCommerce
- [ ] Storefront Powerpack
- [ ] TaxJar - Sales Tax Automation for WooCommerce
- [ ] WooCommerce Australia Post Shipping
- [ ] WooCommerce eWAY Payment Gateway
- [ ] WooCommerce Klarna Gateway
- [ ] WooCommerce Payfast Gateway
- [ ] WooCommerce PayPal Checkout Gateway
- [ ] WooCommerce PayPal Express Gateway
- [ ] WooCommerce Product Add-ons
- [ ] WooCommerce Royal Mail
- [ ] WooCommerce Services
- [ ] WooCommerce Square
- [ ] WooCommerce Stripe Gateway
- [ ] WooCommerce UPS Shipping
- [ ] WooCommerce USPS Shipping

I have also tested the following themes admin notices:
- [ ] Storefront
- [ ] Galleria
- [ ] Homestore
- [ ] Bookshop

This covers all plugin activation messages and wp-admin notices in both regular dashboard and Calypsoified WC areas.

With all 23 plugins active, these are the wp-admin warning messages: https://cloudup.com/cJ1AlSQTqxu
With all 23 plugins active, these are the calypsoified warning messages: https://cloudup.com/c0DnWpsfozE and https://cloudup.com/cjIwsNv-od6
There are some additional notices on activation of the plugins, as seen here: https://cloudup.com/c_RoMF2Sd97
Since adding the suppression actions, all activation messages are gone in the plugin management screen: https://cloudup.com/cpZAPTL2jBn
Since adding the suppression actions, all admin notices are gone in the calypsoified wp-admin: https://cloudup.com/cR6YfZXHOnD
