### ISSUE TITLE
WooCommerce Payments Welcome Screen

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wc-calypso-bridge#679]
**DRAFT: NOT READY TO BE IMPLEMENTED - STILL BEING FINALIZED BY @mattsherman AND TEAM**

## User story

As a merchant that a store on WordPress.com with the eCommerce or Business plan, I want to see the Welcome Screen for WooCommerce Payments if I am not already using it, so that I am aware that it exists and can consider it as the payment gateway for my store.

## Open questions

- What is the experiment? What are the different experiences we are testing?
- Will WooCommerce Payments be auto-installed for existing merchants prior to the Welcome Screen being available, or will the Welcome Screen prompt the merchant to install WooCommerce Payments?

## Acceptance criteria

- TODO

## Tasks

- [ ] Create an ExPlat experiment
- [ ] Register admin menu item for Welcome Screen
- [ ] Implement Welcome Screen, including Tracks events
- [ ] Launch ExPlat experiment

**Comment by mattsherman** [comment]
Closing this -- this placeholder epic was never used. Other issues were created instead.
